version: '2.1'
services:
    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "8888:80"
        networks:
          vpcbr:
            ipv4_address: 172.10.1.10
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - /var/www:/var/www
            - /var/log/nginx:/var/log/nginx
        links:
            - php
    php:
        build: ./images/php
        restart: unless-stopped
        networks:
          vpcbr:
            ipv4_address: 172.10.1.20
        volumes:
            - /var/www:/var/www
    scripts:
        build: ./images/scripts
        restart: unless-stopped
        networks:
          vpcbr:
            ipv4_address: 172.10.1.30
        volumes:
            - /var/log/nginx:/var/log/nginx
        links:
            - nginx
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.10.1.0/16
         gateway: 172.10.1.1
